name: Build and Deploy to Firebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn ci:format
      - run: yarn ci:lint
      - run: yarn ci:test:cy
      - run: yarn build

  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: yarn export
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: out
          path: out

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ci, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: out
          path: out
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
